Fixed ssh auth

diff --git a/nagios-extras/check_robots b/nagios-extras/check_robots
--- a/nagios-extras/check_robots
+++ b/nagios-extras/check_robots
@@ -1,10 +1,14 @@
 #!/bin/bash
 
-COUNT=`wget -O - -q $1/robots.txt |wc -l`
-if [ "$COUNT" -gt 5 ]; then
-    echo "Robots good: $COUNT lines";
-    exit 1;
+wget --no-check-certificate -O - -q https://$1/robots.txt | grep -i "^Disallow: /$">/tmp/debug.log
+SUCCESS=$?
+
+# if [ "$COUNT" -gt 5 ]; then
+if [ "$SUCCESS" == 1 ]; then
+    echo "Good robots: ^Disallow: /\$ not found."
+    exit 0;
 fi
 
-echo "Robots Bad: $COUNT lines";
-exit 0;
+echo "Bad robots: ^Disallow: /\$ found.";
+exit 2;
+
